import { Keyword, MinionType, Type } from "@/types/card";

export const mapType = {
  ["hero"]: Type.Hero,
  ["minion"]: Type.Minion,
  ["spell"]: Type.Spell,
  ["weapon"]: Type.Weapon,
  ["hero power"]: Type.HeroPower,
  ["location"]: Type.Location,
  ["baconquestreward"]: Type.Reward,
  ["anomalies"]: Type.Anomalies,
};

export const keywordMap = {
  ["taunt"]: Keyword.Taunt,
  ["spell-damage"]: Keyword.SpellDamage,
  ["divine-shield"]: Keyword.DivineShield,
  ["charge"]: Keyword.Charge,
  ["secret"]: Keyword.Secret,
  ["stealth"]: Keyword.Stealth,
  ["battlecry"]: Keyword.Battlecry,
  ["freeze"]: Keyword.Freeze,
  ["windfury"]: Keyword.Windfury,
  ["deathrattle"]: Keyword.Deathrattle,
  ["combo"]: Keyword.Combo,
  ["overload"]: Keyword.Overload,
  ["silence"]: Keyword.Silence,
  ["counter"]: Keyword.Counter,
  ["immune"]: Keyword.Immune,
  ["spare-parts"]: Keyword.SpareParts,
  ["inspire"]: Keyword.Inspire,
  ["discover"]: Keyword.Discover,
  ["quest"]: Keyword.Quest,
  ["poisonous"]: Keyword.Poisonous,
  ["adapt"]: Keyword.Adapt,
  ["lifesteal"]: Keyword.Lifesteal,
  ["recruit"]: Keyword.Recruit,
  ["echo"]: Keyword.Echo,
  ["rush"]: Keyword.Rush,
  ["overkill"]: Keyword.Overkill,
  ["start-of-game"]: Keyword.StartOfGame,
  ["magnetic"]: Keyword.Magnetic,
  ["lackey"]: Keyword.Lackey,
  ["twinspell"]: Keyword.Twinspell,
  ["mega-windfury"]: Keyword.MegaWindfury,
  ["reborn"]: Keyword.Reborn,
  ["invoke"]: Keyword.Invoke,
  ["outcast"]: Keyword.Outcast,
  ["spellburst"]: Keyword.Spellburst,
  ["sidequest"]: Keyword.Sidequest,
  ["corrupt"]: Keyword.Corrupt,
  ["questline"]: Keyword.Questline,
  ["tradeable"]: Keyword.Tradeable,
  ["frenzy"]: Keyword.Frenzy,
  ["honorable-kill"]: Keyword.HonorableKill,
  ["nature-spell-damage"]: Keyword.NatureSpellDamage,
  ["blood-gem"]: Keyword.BloodGem,
  ["refresh"]: Keyword.Refresh,
  ["avenge"]: Keyword.Avenge,
  ["colossal"]: Keyword.Colossal,
  ["dredge"]: Keyword.Dredge,
  ["spellcraft"]: Keyword.Spellcraft,
  ["infuse"]: Keyword.Infuse,
  ["corpse"]: Keyword.Corpse,
  ["finale"]: Keyword.Finale,
  ["overheal"]: Keyword.Overheal,
  ["manathirst"]: Keyword.Manathirst,
  ["venomous"]: Keyword.Venomous,
  ["elusive"]: Keyword.Elusive,
  ["forge"]: Keyword.Forge,
  ["titan"]: Keyword.Titan,
  ["miniaturize"]: Keyword.Miniaturize,
  ["mini"]: Keyword.Mini,
  ["quickdraw"]: Keyword.Quickdraw,
  ["excavate"]: Keyword.Excavate,
  ["pass"]: Keyword.Pass,
};

export const minionMap = {
  ["bloodelf"]: MinionType.BloodElf,
  ["draenei"]: MinionType.Draenei,
  ["dwarf"]: MinionType.Dwarf,
  ["gnome"]: MinionType.Gnome,
  ["human"]: MinionType.Human,
  ["nightelf"]: MinionType.NightElf,
  ["orc"]: MinionType.Orc,
  ["tauren"]: MinionType.Tauren,
  ["troll"]: MinionType.Troll,
  ["undead"]: MinionType.Undead,
  ["murloc"]: MinionType.Murloc,
  ["demon"]: MinionType.Demon,
  ["mech"]: MinionType.Mech,
  ["elemental"]: MinionType.Elemental,
  ["beast"]: MinionType.Beast,
  ["totem"]: MinionType.Totem,
  ["pirate"]: MinionType.Pirate,
  ["dragon"]: MinionType.Dragon,
  ["all"]: MinionType.All,
  ["quilboar"]: MinionType.Quilboar,
  ["halforc"]: MinionType.HalfOrc,
  ["naga"]: MinionType.Naga,
  ["oldgod"]: MinionType.OldGod,
  ["pandaren"]: MinionType.Pandaren,
  ["gronn"]: MinionType.Gronn,
};
