import { Keyword } from "@/types/card";

export const keywordMapper: Record<Keyword, string> = {
  [Keyword.Taunt]: "Enemies must attack minions that have Taunt.",
  [Keyword.SpellDamage]: "Your spells deal extra damage.",
  [Keyword.DivineShield]:
    "The first time a Shielded minion takes damage, ignore it.",
  [Keyword.Charge]: "Can attack immediately.",
  [Keyword.Secret]:
    "Hidden until a specific action occurs on your opponent's turn.",
  [Keyword.Stealth]: "Can't be attacked or targeted until it attacks.",
  [Keyword.Battlecry]: "Does something when you play it from your hand.",
  [Keyword.Freeze]: "Frozen characters lose their next attack.",
  [Keyword.Windfury]: "Can attack twice each turn.",
  [Keyword.Deathrattle]: "Does something when it dies.",
  [Keyword.Combo]: "A bonus if you already played a card this turn.",
  [Keyword.Overload]: "Cards with Overload limit your mana next turn.",
  [Keyword.Silence]: "Removes all card text and enchantments.",
  [Keyword.Counter]: "A card that is Countered has no effect.",
  [Keyword.Immune]: "Immune characters can't be damaged.",
  [Keyword.SpareParts]: "Spare Parts are 1-Cost spells with minor effects.",
  [Keyword.Inspire]: "Does something after you use your Hero Power.",
  [Keyword.Discover]: "Choose one of three cards to add to your hand.",
  [Keyword.Quest]: "Starts in your hand. Complete for a reward.",
  [Keyword.Poisonous]: "Destroy any minion damaged by this.",
  [Keyword.Adapt]: "Choose one of 3 bonuses.",
  [Keyword.Lifesteal]: "Damage dealt also heals your hero.",
  [Keyword.Recruit]: "Summon a minion from your deck.",
  [Keyword.Echo]:
    "Repeatable the turn you play this. Copies can't cost less than (1).",
  [Keyword.Rush]: "Can attack minions immediately.",
  [Keyword.Overkill]: "Deal excess damage on your turn for a bonus.",
  [Keyword.StartOfGame]: "Does something before the first turn.",
  [Keyword.Magnetic]: "Play this to the left of a Mech to fuse them together!",
  [Keyword.Lackey]: "Lackeys are 1-Cost minions with Battlecries.",
  [Keyword.Twinspell]: "Can be cast twice.",
  [Keyword.MegaWindfury]: "Can attack four times each turn.",
  [Keyword.Reborn]: "Resurrects with 1 Health the first time it dies.",
  [Keyword.Invoke]: "Use Galakrond's Power.",
  [Keyword.Outcast]:
    "A bonus if played as the left- or right-most card in hand.",
  [Keyword.Spellburst]: "A one-time effect after you cast a spell.",
  [Keyword.Sidequest]: "Complete for a reward.",
  [Keyword.Corrupt]: "Upgrades in hand after you play a card that costs more.",
  [Keyword.Questline]:
    "Starts in your hand. Complete for a reward, up to 3 times!",
  [Keyword.Tradeable]:
    "Drag this into your deck to spend 1 Mana and draw a new card.",
  [Keyword.Frenzy]: "A one-time effect after this survives damage.",
  [Keyword.HonorableKill]: "Deal exact lethal damage on your turn for a bonus.",
  [Keyword.NatureSpellDamage]: "Your Nature spells deal extra damage.",
  [Keyword.BloodGem]: "A spell that gives a minion .",
  [Keyword.Refresh]: "Replace the Tavern with new cards.",
  [Keyword.Avenge]: "Does something after X friendly minions die in combat.",
  [Keyword.Colossal]: "When summoned, spawns X additional appendages.",
  [Keyword.Dredge]: "Look at the bottom 3 cards of your deck. Put one on top.",
  [Keyword.Spellcraft]: "Get a temporary spell every turn.",
  [Keyword.Infuse]: "Upgrades in hand after X friendly minions die.",
  [Keyword.Corpse]: "Resource gained when a friendly minion dies.",
  [Keyword.Finale]: "A bonus if this spends all your remaining Mana.",
  [Keyword.Overheal]: "A bonus if restored past full Health.",
  [Keyword.Manathirst]: "A bonus if you have X Mana Crystals.",
  [Keyword.Venomous]: "Destroy the first minion this deals damage to.",
  [Keyword.Elusive]: "Can't be targeted by spells or Hero Powers.",
  [Keyword.Forge]: "Drag this to your deck to spend (2) Mana for an upgrade.",
  [Keyword.Titan]:
    "Click on a Titan to use 1 of 3 abilities instead of attacking.",
  [Keyword.Miniaturize]: "Get a 1-Cost 1/1 copy of this.",
  [Keyword.Mini]: "A 1-Cost 1/1 copy of another card.",
  [Keyword.Quickdraw]: "A bonus if this entered your hand this turn.",
  [Keyword.Excavate]:
    "Dig for increasingly rarer treasures. Resets after the highest Rarity.",
  [Keyword.Pass]: "Send to your teammate's hand.",
};
